Cambios varios
RoMaIsau/SmartFarm pull request #3
Opened 2020-06-01 03:34 UTC by Mury10

1) A "/validar-registro" (está en "ControladorUsuario") se le modificó la consulta en el DAO. Quité el password como un criterio de búsqueda ya que esto permitía que puedan existir 2 usuarios con el mismo e-mail pero diferente contraseña.

2) Descarté el que los tipos de usuarios se hagan con herencia ya que al tratar de implementar una forma de hacerlo herencia más daba en el caso de que estos 3 tipos de empleados por si solos no tendrían datos que los separen de los otros (a nivel DER) sino métodos y esto ya correspondería a lo que hagamos a nivel código de JAVA.

3) Se agrega a la parte de estadísticas (que estimo eran las de la contabilidad que hace el ADMIN) el código para que al entrar a dicha sección se muestren todos los registros. Mi idea era filtrarlos para que únicamente muestre los del usuario logueado pero la consulta no funciona (la dejé comentada en su correspondiente repositorio).

2020-06-01 12:00 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/controladores/ControladorAdmin.java
> +
¿Por que dejaste tantos enters?

2020-06-01 12:01 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/controladores/ControladorAdmin.java
> +
Acá también.

2020-06-01 12:02 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/controladores/ControladorUsuario.java
> +										@RequestParam(name = "password2") String password2) {
No deberíamos recibir una password por GET

2020-06-01 12:04 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/repositorios/RepositorioGastos.java
> +	List<Gastos> consultarGastosPorUsuario(String idEncontrado);
¿Que es idEncontrado?  ¿Por que es un String?

2020-06-01 12:05 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/repositorios/RepositorioGastosImpl.java
> +			.add(Restrictions.eq("usuariojoin.id", idEncontrado))
Si idEncontrado hace referencia al id de usuario capaz conviene pasar un Long y listo.

2020-06-01 12:07 UTC, RoMaIsau commented on src/main/resources/hibernateContext.xml
>  	</bean>
Esto está mal. Deja los valores que estaban antes y que tenemos todos. Create una base de datos propia de smart farm. Cada uno tiene su usuario root con su propia pass.

2020-06-01 12:09 UTC, RoMaIsau commented on src/main/webapp/WEB-INF/vistas/estadisticas.jsp
> +
No se si es github que me muestra tantos enters...

2020-06-01 12:09 UTC, RoMaIsau commented on src/main/webapp/WEB-INF/vistas/estadisticas.jsp
> +
Idem anterior

2020-06-01 12:10 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/controladores/ControladorUsuario.java
> +
Acá también.

2020-06-01 12:12 UTC, RoMaIsau requested changes
Hay algunas cosas ahí con los enters.

Y lo del usuario y contraseña de base de datos

2020-06-01 12:23 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/repositorios/RepositorioUsuarioImpl.java
> +		return (Usuario) session.createCriteria(Usuario.class).add(Restrictions.eq("email", usuario.getEmail())).uniqueResult();
¿Esta consulta es para el login? Si es así poniendo cualquier contraseña pero un email  existente en la base de datos me logueo...

2020-06-03 01:18 UTC, Mury10 commented on src/main/java/ar/edu/unlam/tallerweb1/controladores/ControladorAdmin.java
> +
Ro, te respondo todas las preguntas en esta sola:

-¿Por que dejaste tantos enters?
-Porque quería separar lo que estaba hecho de lo que quería agregar, o sea, cuando scrolleo no perder tiempo en encontrar la sección.

-No deberíamos recibir una password por GET
-Lo modifico, esa parte del código sólo la modifiqué por lo que aclaré, si se verifica que exista el usuario con contraseña permite que haya 2 con el mismo e-mail, lo comprobé manualmente.

-Si idEncontrado hace referencia al id de usuario capaz conviene pasar un Long y listo.
-Vuelvo a verificarlo entonces. Cuando lo hice de tipo Long esa variable me saltaba un error 500 de que no podía (si mal no recuerdo) castearlo a ese tipo. Como dije, lo vuelvo a verificar.

-Esto está mal. Deja los valores que estaban antes y que tenemos todos. Create una base de datos propia de smart farm. Cada uno tiene su usuario root con su propia pass.
-Ok, lo hago.

-¿Esta consulta es para el login? Si es así poniendo cualquier contraseña pero un email existente en la base de datos me logueo...
-No no, ese es para el registro, tal como dije antes, vos si al registrar evaluás que esté el e-mail y la contraseña estás dejando a la posibilidad de que se registre otra persona con el mismo e-mail pero contraseña diferente, eso es al momento de querer cargarlo en la DB.

2020-06-03 01:31 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/repositorios/RepositorioUsuarioImpl.java
> +		return (Usuario) session.createCriteria(Usuario.class).add(Restrictions.eq("email", usuario.getEmail())).uniqueResult();
Miré el código y esta consulta se usa en el login.
En el jsp dice: <form:form action="validar-login" method="POST">

En el controller dice:
	@RequestMapping(path = "/validar-login", method = RequestMethod.POST)
	public ModelAndView validarLogin(@ModelAttribute("usuario") Usuario usuario, HttpServletRequest request) {
		ModelMap model = new ModelMap();
		Usuario usuarioBuscado = servicioUsuario.consultarUsuario(usuario);

El servicio usuario dice: return servicioUsuarioDao.consultarUsuario(usuario);

Así que me parece que dejaste de validar el password y que solo con un email que exista en la base alcanza para hacer login. ¿O cambiaste el controlador y no veo el cambio?

2020-06-03 01:37 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/controladores/ControladorAdmin.java
> +
Ahí te respondí lo del login. Si trataste de arreglar un bug quizás esta mal la parte del registro, pero me parece que tocaste una consulta que se usa para loguearse. Fijate en el comentario el código que pegue.

Lo del hibernate context es para que no tengamos que estar constantemente poniendo el usuario (root) que cada uno tiene en su máquina. Para crear la base de datos en el cliente sql que uses, esta el script: CrearBaseDeDatos.sql  Esta commiteado junto al proyecto.

Creo que se perdería mas tiempo al scrollear por tener tantos enters.

2020-06-03 14:31 UTC, RoMaIsau commented
Lo mergeo a master pero hay que arreglar lo del login que con este cambio queda roto, los espacios en blanco y lo de la base de datos.

2020-06-03 14:32 UTC, merged