Agustina2
RoMaIsau/SmartFarm pull request #7
Opened 2020-06-21 01:02 UTC by AgusBaudach

2020-06-21 02:32 UTC, RoMaIsau requested changes

2020-06-21 02:32 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/modelo/AnimalDeGranja.java
> -
Consulta, ¿Por que se borró el equals y el hashcode? Se está usando.

2020-06-21 02:32 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/modelo/AnimalDeGranja.java
> +	private List<Vacuna> vacunasParaAplicar=new ArrayList<Vacuna>();
Consulta... ¿No conviene usar una clase intermedia en lugar del ManyToMany? De esta manera no vamos a poder tener info adicional onda la fecha, si fue aplicada o no, cosas de ese estilo

2020-06-21 02:32 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/modelo/HistoriaClinica.java
> +	List<SignosVitales>signos;
Andrés nos dijo varias veces que esto del OneToMany no está bueno. ¿Esto es así por algún motivo particular? ¿No podemos resolverlo de otra manera?

2020-06-21 02:32 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/modelo/AnimalDeGranja.java
> +	private List<Vacuna> vacunasParaAplicar=new ArrayList<Vacuna>();
Acabo de ver que está la entity Vacunar. Entonces este ManyToMany está de mas, habría que sacarlo.

2020-06-21 02:32 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/servicios/ServicioVacunaImpl.java
> +			edadVacaMeses= (a�os*12)+actual.get(Calendar.MONTH)-fechaNacimiento.get(Calendar.MONTH);
Creo que travis está rompiendo porque falla el encoding. Quizás convenga quitar las ñ o fijate como hacer que acepte este tipo de caracteres.

2020-06-27 00:17 UTC, AgusBaudach commented on src/main/java/ar/edu/unlam/tallerweb1/modelo/AnimalDeGranja.java
> +	private List<Vacuna> vacunasParaAplicar=new ArrayList<Vacuna>();
Ese lo uso para la alarma vacuna!! No lo puedo cambiar. Supongo que por uno solo no va a decir nada!! La clase vacunar la uso para las vacunas aplicadas...

2020-06-27 00:18 UTC, AgusBaudach commented on src/main/java/ar/edu/unlam/tallerweb1/modelo/HistoriaClinica.java
> +	List<SignosVitales>signos;
Si, este ya lo estoy cambiando!! cambie unos cuantos joins, ya lo termino...

2020-06-27 00:18 UTC, AgusBaudach commented on src/main/java/ar/edu/unlam/tallerweb1/servicios/ServicioVacunaImpl.java
> +			edadVacaMeses= (a�os*12)+actual.get(Calendar.MONTH)-fechaNacimiento.get(Calendar.MONTH);
lo cambie por la palabra anios

2020-06-27 00:19 UTC, AgusBaudach commented on src/main/java/ar/edu/unlam/tallerweb1/modelo/AnimalDeGranja.java
> -
yo no lo saque, fue git jajaj!!! Ya lo volvi a pegar...

2020-06-27 13:43 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/modelo/AnimalDeGranja.java
> -
Seguía sin estar así que lo agregué yo

2020-06-27 13:45 UTC, RoMaIsau commented on src/main/java/ar/edu/unlam/tallerweb1/servicios/ServicioVacunaImpl.java
> +			edadVacaMeses= (a�os*12)+actual.get(Calendar.MONTH)-fechaNacimiento.get(Calendar.MONTH);
Pero comiteaste? Porque sigue rompiendo lo mismo. Lo cambie y lo subí. Tb ajuste el encoding del proyecto asi podes usar ñ

2020-06-27 13:46 UTC, RoMaIsau commented
Falta arreglar el test que rompe y en teoría se podría mergear. Si necesitas ayuda avisanos

2020-06-30 19:22 UTC, merged